-- MySQL Script generated by MySQL Workbench
-- Wed May  8 09:43:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cataloguei_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cataloguei_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cataloguei_shop` DEFAULT CHARACTER SET utf8 ;
USE `cataloguei_shop` ;

-- -----------------------------------------------------
-- Table `cataloguei_shop`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cataloguei_shop`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `uf` VARCHAR(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cataloguei_shop`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cataloguei_shop`.`empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(180) NULL,
  `senha` VARCHAR(180) NULL,
  `nome` VARCHAR(60) NULL,
  `descricao` VARCHAR(180) NULL,
  `path_logo` VARCHAR(200) NULL,
  `numero_whatsapp` VARCHAR(22) NULL,
  `dominio` VARCHAR(60) NULL,
  `status` VARCHAR(45) NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empresa_cidade1_idx` (`cidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_empresa_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `cataloguei_shop`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cataloguei_shop`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cataloguei_shop`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(180) NULL,
  `senha` VARCHAR(180) NULL,
  `nome` VARCHAR(120) NULL,
  `cpf` VARCHAR(14) NULL,
  `numero_whatsapp` VARCHAR(20) NULL,
  `path_img` VARCHAR(200) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cataloguei_shop`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cataloguei_shop`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo_barras` VARCHAR(14) NULL,
  `nome` VARCHAR(60) NULL,
  `descricao` VARCHAR(200) NULL,
  `preco` DECIMAL NULL,
  `path_imagem` VARCHAR(200) NULL,
  `estoque` DECIMAL NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cataloguei_shop`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cataloguei_shop`.`venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_venda` DATE NULL,
  `hora_venda` TIME NULL,
  `total` DECIMAL NULL,
  `status` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  `empresa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venda_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_venda_empresa1_idx` (`empresa_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cataloguei_shop`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `cataloguei_shop`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cataloguei_shop`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cataloguei_shop`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `rua` VARCHAR(60) NULL,
  `complemento` VARCHAR(60) NULL,
  `usuario_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_endereco_cidade1_idx` (`cidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cataloguei_shop`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `cataloguei_shop`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cataloguei_shop`.`venda_detalhe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cataloguei_shop`.`venda_detalhe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `qtd` DECIMAL NULL,
  `valor_un` DECIMAL NULL,
  `valor_total` DECIMAL NULL,
  `status` VARCHAR(45) NULL,
  `obs` VARCHAR(80) NULL,
  `venda_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venda_detalhe_venda1_idx` (`venda_id` ASC) VISIBLE,
  INDEX `fk_venda_detalhe_produto1_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_detalhe_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `cataloguei_shop`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_detalhe_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `cataloguei_shop`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
